---
- name: Check if wezterm is installed
  command: which wezterm
  register: wezterm_installed
  changed_when: false
  failed_when: false

- name: Add wezterm GPG key
  ansible.builtin.shell: |
    curl -fsSL https://apt.fury.io/wez/gpg.key | sudo gpg --yes --dearmor -o /usr/share/keyrings/wezterm-fury.gpg
  args:
    creates: /usr/share/keyrings/wezterm-fury.gpg
  become: false
  when: wezterm_installed.rc != 0

- name: Add wezterm apt repository
  copy:
    content: "deb [signed-by=/usr/share/keyrings/wezterm-fury.gpg] https://apt.fury.io/wez/ * *"
    dest: /etc/apt/sources.list.d/wezterm.list
    mode: "0644"
  become: true
  when: wezterm_installed.rc != 0

- name: Set permissions on wezterm GPG key
  file:
    path: /usr/share/keyrings/wezterm-fury.gpg
    mode: "0644"
  become: true
  when: wezterm_installed.rc != 0

- name: Update apt cache
  apt:
    update_cache: yes
  become: true
  when: wezterm_installed.rc != 0

- name: Install wezterm
  apt:
    name: wezterm
    state: present
  become: true
  when: wezterm_installed.rc != 0

- name: Ensure .config/wezterm directory exists
  file:
    path: "{{ user_home }}/.config/wezterm"
    state: directory
    mode: "0755"
  become: false

- name: Create symbolic link for wezterm config
  file:
    src: "{{ user_home }}/dotfiles-popos/config/wezterm/wezterm.lua"
    dest: "{{ user_home }}/.config/wezterm/wezterm.lua"
    state: link
  become: false
