- hosts: localhost
  connection: local
  gather_facts: true
  become: false

  vars:
    user_home: "{{ lookup('env', 'HOME') }}"

  tasks:
    - name: Update apt cache
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install basic packages
      become: true
      apt:
        name:
          - curl
          - tree
        state: present

    - name: Stat nvim source directory
      stat:
        path: "{{ user_home }}/dotfiles/config/nvim"
      register: nvim_src

    - name: Stat nvim destination directory
      stat:
        path: "{{ user_home }}/.config/nvim"
      register: nvim_dest

    - name: Ensure .config directory exists
      file:
        path: "{{ user_home }}/.config"
        state: directory
        mode: '0755'
      become: false

  roles:
    - fcitx5
    - gnome
    - fonts
    - zsh
    - themes
    - develop
    - vscode
    - neovim
    - languages/rust
    - alacritty
    - wezterm
